# Generated by Django 3.2.11 on 2022-03-14 14:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(choices=[('Our Opinions', 'Our Opinions'), ('Our Advantages', 'Our Advantages'), ('Our Future', 'Our Future'), ('Recruits', 'Recruits')], default='Our Opinions', max_length=255, verbose_name='文章分类')),
                ('navigation', models.CharField(default='关于我们', max_length=255, verbose_name='页面内标题')),
                ('page_intro', models.CharField(default='简要介绍', max_length=512, verbose_name='页面简要介绍')),
                ('page_type', models.CharField(default='观点', max_length=20, verbose_name='文章类型')),
                ('content_stream', wagtail.fields.StreamField([('source_code', wagtail.blocks.RawHTMLBlock()), ('big_title', wagtail.blocks.CharBlock(help_text='大标题', max_length=512)), ('content', wagtail.blocks.ListBlock(wagtail.blocks.RichTextBlock(help_text='内容'), help_text='这里可以填入多个内容，也可以只填写一个')), ('author_info', wagtail.blocks.StructBlock([('ico_image', wagtail.images.blocks.ImageChooserBlock(help_text='头像')), ('author_name', wagtail.blocks.CharBlock(help_text='作者', max_length=255)), ('author_intro', wagtail.blocks.CharBlock(help_text='作者介绍', max_length=255))], blank=True, help_text='作者信息', max_num=1, null=True))], blank=True, null=True)),
                ('page_intro_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='首页内容介绍图片')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CompanyIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('index_ask_title', models.CharField(default='XXX', max_length=25, verbose_name='首页咨询标题')),
                ('index_ask_info', models.CharField(default='XXX', max_length=50, verbose_name='首页咨询内容')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CompanyRecruitsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('info', wagtail.fields.RichTextField(blank=True, null=True)),
                ('campus_intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='校园招聘介绍')),
                ('social_intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='社会招聘介绍')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CompanySecondPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CompanyThirdPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CompanyThirdPageBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('info', models.CharField(blank=True, max_length=250)),
                ('info_title', models.CharField(blank=True, max_length=250)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='wagtail_apps.companythirdpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanySecondPageBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('info', models.CharField(blank=True, max_length=250)),
                ('info_title', models.CharField(blank=True, max_length=250)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='wagtail_apps.companysecondpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyRecruitsPageBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('info', models.CharField(blank=True, max_length=250)),
                ('info_title', models.CharField(blank=True, max_length=250)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='wagtail_apps.companyrecruitspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyIndexPageBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('info', models.CharField(blank=True, max_length=250)),
                ('info_title', models.CharField(blank=True, max_length=250)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='wagtail_apps.companyindexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyContentPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='介绍')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('child_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_images', to='wagtail_apps.companycontentpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
