# Generated by Django 3.0.6 on 2021-12-12 15:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('navigation', models.CharField(default='关于我们', max_length=255, verbose_name='页面内标题')),
                ('page_intro', models.CharField(default='简要介绍', max_length=512, verbose_name='页面简要介绍')),
                ('content_stream', wagtail.core.fields.StreamField([('source_code', wagtail.core.blocks.RawHTMLBlock()), ('big_title', wagtail.core.blocks.CharBlock(help_text='大标题', max_length=512)), ('content', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(help_text='内容'), help_text='这里可以填入多个内容，也可以只填写一个')), ('author_info', wagtail.core.blocks.StructBlock([('ico_image', wagtail.images.blocks.ImageChooserBlock(help_text='头像')), ('author_name', wagtail.core.blocks.CharBlock(help_text='作者', max_length=255)), ('author_intro', wagtail.core.blocks.CharBlock(help_text='作者介绍', max_length=255))], blank=True, help_text='作者信息', max_num=1, null=True))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CompanyContentPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('info', models.CharField(blank=True, max_length=250, null=True, verbose_name='介绍')),
                ('title', models.CharField(blank=True, max_length=10, null=True, verbose_name='标题')),
                ('child_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_images', to='company_content_page.CompanyContentPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
