# Generated by Django 3.0.6 on 2021-12-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_content_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontentpage',
            name='page_intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='封面介绍图'),
        ),
    ]
