# Generated by Django 3.0.6 on 2021-12-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('company_content_page', '0002_companycontentpage_page_intro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontentpage',
            name='page_intro_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='首页内容介绍图片'),
        ),
    ]
