# Generated by Django 3.0.6 on 2021-12-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_content_page', '0003_auto_20211212_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontentpage',
            name='category',
            field=models.CharField(choices=[('Our Opinions', 'Our Opinions'), ('Our Advantages', 'Our Advantages'), ('Our Future', 'Our Future')], default='Our Opinions', max_length=255, verbose_name='文章分类'),
        ),
    ]
