# Generated by Django 3.0.6 on 2021-12-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_content_page', '0006_auto_20211213_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontentpageimage',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='companycontentpageimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标题'),
        ),
    ]
