# Generated by Django 3.0.6 on 2022-01-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_content_page', '0007_auto_20211214_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontentpage',
            name='page_type',
            field=models.CharField(default='观点', max_length=20, verbose_name='文章类型'),
        ),
    ]
