# Generated by Django 3.0.6 on 2022-01-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_content_page', '0008_companycontentpage_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontentpage',
            name='category',
            field=models.CharField(choices=[('Our Opinions', 'Our Opinions'), ('Our Advantages', 'Our Advantages'), ('Our Future', 'Our Future'), ('Recruits', 'Recruits')], default='Our Opinions', max_length=255, verbose_name='文章分类'),
        ),
    ]
