# Generated by Django 3.0.6 on 2022-01-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_recruits_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrecruitspage',
            name='campus_intro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='校园招聘介绍'),
        ),
        migrations.AddField(
            model_name='companyrecruitspage',
            name='social_intro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='社会招聘介绍'),
        ),
    ]
