# Generated by Django 3.2.11 on 2023-06-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_apps', '0005_auto_20220627_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlastStorckMarketData',
            new_name='BlastStockMarketData',
        ),
    ]
