# Generated by Django 3.2.11 on 2023-06-12 09:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtail_apps', '0005_alter_companycontentpage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontentpage',
            name='content_stream',
            field=wagtail.fields.StreamField([('source_code', wagtail.blocks.RawHTMLBlock()), ('big_title', wagtail.blocks.CharBlock(help_text='大标题', max_length=512)), ('content', wagtail.blocks.ListBlock(wagtail.blocks.RichTextBlock(help_text='内容'), help_text='这里可以填入多个内容，也可以只填写一个')), ('author_info', wagtail.blocks.StructBlock([('ico_image', wagtail.images.blocks.ImageChooserBlock(help_text='头像')), ('author_name', wagtail.blocks.CharBlock(help_text='作者', max_length=255)), ('author_intro', wagtail.blocks.CharBlock(help_text='作者介绍', max_length=255))], blank=True, help_text='作者信息', max_num=1, null=True))], blank=True, null=True, use_json_field=True),
        ),
        migrations.CreateModel(
            name='CompanyDailyContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(default='Daily', max_length=255, verbose_name='文章分类')),
                ('navigation', models.CharField(default='每日财报', max_length=255, verbose_name='页面内标题')),
                ('page_intro', models.CharField(default='简要介绍', max_length=512, verbose_name='页面简要介绍')),
                ('body', wagtail.fields.StreamField([('source_code', wagtail.blocks.RawHTMLBlock()), ('big_title', wagtail.blocks.CharBlock(help_text='大标题', max_length=512)), ('content', wagtail.blocks.RichTextBlock(help_text='内容')), ('ico_image', wagtail.images.blocks.ImageChooserBlock(help_text='头像')), ('author_name', wagtail.blocks.CharBlock(help_text='作者', max_length=255)), ('author_intro', wagtail.blocks.CharBlock(help_text='作者介绍', max_length=255))], blank=True, use_json_field=True, verbose_name='Page body')),
                ('image', models.ForeignKey(blank=True, help_text='内容页图片', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page_intro_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='首页内容介绍图片')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
