# Generated by Django 3.0.6 on 2021-11-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0002_auto_20211102_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysitepagebannerimage',
            old_name='image',
            new_name='banner_image',
        ),
    ]
