# Generated by Django 3.0.6 on 2021-11-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0003_auto_20211102_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysitepagebannerimage',
            name='url',
            field=models.URLField(default='#'),
        ),
    ]
