# Generated by Django 3.0.6 on 2021-11-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0004_companysitepagebannerimage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysitepagebannerimage',
            name='url',
        ),
    ]
