# Generated by Django 3.0.6 on 2021-11-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0006_companysitepageindeximage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysitepageindeximage',
            name='info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
