# Generated by Django 3.0.6 on 2021-11-03 15:09

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0007_auto_20211103_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysitepageindeximage',
            old_name='index_image',
            new_name='advantages_image',
        ),
        migrations.RemoveField(
            model_name='companysitepage',
            name='body',
        ),
        migrations.AddField(
            model_name='companysitepageindeximage',
            name='title',
            field=models.CharField(default='产品优势', max_length=10, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='companysitepageindeximage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages_images', to='companysite.CompanySitePage'),
        ),
    ]
