# Generated by Django 3.0.6 on 2021-11-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('companysite', '0008_auto_20211103_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanySitePageIndexImage',
            new_name='CompanySitePageAdvantagesImage',
        ),
    ]
