# Generated by Django 3.0.6 on 2021-11-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0009_auto_20211103_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysitepage',
            name='index_ask_info',
            field=models.CharField(default='XXX', max_length=50, verbose_name='首页咨询内容'),
        ),
        migrations.AddField(
            model_name='companysitepage',
            name='index_ask_title',
            field=models.CharField(default='XXX', max_length=25, verbose_name='首页咨询标题'),
        ),
    ]
