# Generated by Django 3.0.6 on 2021-11-04 10:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('companysite', '0011_companysitechildpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysitechildpage',
            name='top_image',
        ),
        migrations.RemoveField(
            model_name='companysitechildpage',
            name='top_image_info',
        ),
        migrations.CreateModel(
            name='CompanySiteChildPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('info', models.CharField(blank=True, max_length=250, null=True, verbose_name='介绍')),
                ('title', models.CharField(blank=True, max_length=10, null=True, verbose_name='标题')),
                ('child_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_images', to='companysite.CompanySiteChildPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
