# Generated by Django 3.0.6 on 2021-11-04 15:42

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0012_auto_20211104_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysitechildpage',
            old_name='body',
            new_name='company_info',
        ),
        migrations.AddField(
            model_name='companysitechildpage',
            name='honor_info',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
