# Generated by Django 3.0.6 on 2021-11-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0013_auto_20211104_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysitechildpage',
            old_name='company_info',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='companysitechildpage',
            name='honor_info',
        ),
        migrations.AddField(
            model_name='companysitechildpage',
            name='site',
            field=models.CharField(default='关于我们', max_length=255, verbose_name='标题'),
        ),
    ]
