# Generated by Django 3.0.6 on 2021-11-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0014_auto_20211104_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysitechildpage',
            old_name='site',
            new_name='navigation',
        ),
    ]
