# Generated by Django 3.0.6 on 2021-12-12 12:27

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0015_auto_20211104_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysitechildpage',
            name='content',
        ),
        migrations.AddField(
            model_name='companysitechildpage',
            name='content_stream',
            field=wagtail.core.fields.StreamField([('source_code', wagtail.core.blocks.RawHTMLBlock()), ('big_title', wagtail.core.blocks.CharBlock(help_text='大标题', max_length=512)), ('content', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(help_text='内容'), help_text='这里可以填入多个内容，也可以只填写一个')), ('author_info', wagtail.core.blocks.StructBlock([('ico_image', wagtail.images.blocks.ImageChooserBlock(help_text='头像')), ('author_name', wagtail.core.blocks.CharBlock(help_text='作者', max_length=255)), ('author_intro', wagtail.core.blocks.CharBlock(help_text='作者介绍', max_length=255))], blank=True, help_text='作者信息', max_num=1, null=True))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companysitechildpage',
            name='navigation',
            field=models.CharField(default='关于我们', max_length=255, verbose_name='页面内标题'),
        ),
    ]
