# Generated by Django 3.0.6 on 2021-11-05 09:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0015_auto_20211104_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysitechildpage',
            name='stream',
            field=wagtail.core.fields.StreamField([('source_code', wagtail.core.blocks.RawHTMLBlock()), ('info', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True),
        ),
    ]
