# Generated by Django 3.0.6 on 2021-11-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0016_companysitechildpage_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysitechildpage',
            name='navigation',
            field=models.CharField(default='关于我们', max_length=255, verbose_name='页面内标题'),
        ),
    ]
