# Generated by Django 3.0.6 on 2021-12-09 14:43

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0017_auto_20211111_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysitechildpage',
            name='stream',
            field=wagtail.core.fields.StreamField([('source_code', wagtail.core.blocks.RawHTMLBlock()), ('info', wagtail.core.blocks.RichTextBlock(help_text='内容')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='头像')), ('big_title', wagtail.core.blocks.CharBlock(help_text='大标题', max_length=512)), ('author_name', wagtail.core.blocks.CharBlock(help_text='作者', max_length=255)), ('author_intro', wagtail.core.blocks.CharBlock(help_text='作者介绍', max_length=255))], blank=True, null=True),
        ),
    ]
