# Generated by Django 4.2.7 on 2026-01-28 17:17

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, null=True, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='职位')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='员工编号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='登录次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('groups', models.ManyToManyField(blank=True, help_text='该用户所属的组。', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='组')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='该用户拥有的特定权限。', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='用户权限')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users_customuser',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='省份')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='邮编')),
                ('wechat', models.CharField(blank=True, max_length=50, null=True, verbose_name='微信号')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ号')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('language', models.CharField(default='zh-cn', max_length=10, verbose_name='语言')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区')),
                ('theme', models.CharField(choices=[('light', '浅色'), ('dark', '深色'), ('auto', '自动')], default='light', max_length=20, verbose_name='主题')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='短信通知')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='推送通知')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.customuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'users_userprofile',
            },
        ),
    ]
