# Generated by Django 4.2.7 on 2026-01-30 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='职位名称')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='部门')),
                ('job_category', models.CharField(choices=[('quant_dev', '量化开发'), ('data_engineer', '数据工程师'), ('risk_manager', '风控专员'), ('researcher', '研究员'), ('it_support', 'IT支持'), ('other', '其他')], max_length=50, verbose_name='职位类别')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='工作地点')),
                ('salary_min', models.CharField(blank=True, max_length=20, verbose_name='最低薪资')),
                ('salary_max', models.CharField(blank=True, max_length=20, verbose_name='最高薪资')),
                ('salary_display', models.CharField(blank=True, max_length=50, verbose_name='薪资显示')),
                ('description', models.TextField(verbose_name='职位描述')),
                ('requirements', models.TextField(verbose_name='任职要求')),
                ('responsibilities', models.TextField(blank=True, verbose_name='工作职责')),
                ('experience', models.CharField(blank=True, max_length=50, verbose_name='经验要求')),
                ('education_required', models.CharField(blank=True, choices=[('high_school', '高中'), ('associate', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], max_length=20, verbose_name='学历要求')),
                ('headcount', models.IntegerField(default=1, verbose_name='招聘人数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '招聘中'), ('paused', '暂停招聘'), ('closed', '已关闭')], default='draft', max_length=20, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
            ],
            options={
                'verbose_name': '职位管理',
                'verbose_name_plural': '职位管理',
                'db_table': 'users_jobposition',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='头像')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=10, null=True, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='职位')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='员工ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='省份')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='邮编')),
                ('wechat', models.CharField(blank=True, max_length=50, null=True, verbose_name='微信号')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ号')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('login_count', models.IntegerField(default=0, verbose_name='登录次数')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('language', models.CharField(default='zh-cn', max_length=10, verbose_name='语言')),
                ('timezone_str', models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区')),
                ('theme', models.CharField(choices=[('light', '浅色'), ('dark', '深色'), ('auto', '自动')], default='light', max_length=20, verbose_name='主题')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='短信通知')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='推送通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'users_userprofile',
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('individual', '个人投资者'), ('institutional', '机构投资者'), ('partner', '合作伙伴'), ('recruiter', '求职者'), ('media', '媒体'), ('other', '其他')], default='individual', max_length=30, verbose_name='用户类别')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='公司/机构名称')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='职位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户类别',
                'verbose_name_plural': '用户类别',
                'db_table': 'users_usercategory',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('job_category', models.CharField(choices=[('quant_dev', '量化开发'), ('data_engineer', '数据工程师'), ('risk_manager', '风控专员'), ('researcher', '研究员'), ('it_support', 'IT支持'), ('other', '其他')], default='other', max_length=50, verbose_name='应聘职位类别')),
                ('expected_salary', models.CharField(blank=True, max_length=50, verbose_name='期望薪资')),
                ('education', models.CharField(blank=True, choices=[('high_school', '高中'), ('associate', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], max_length=20, verbose_name='最高学历')),
                ('school', models.CharField(blank=True, max_length=100, verbose_name='毕业院校')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='专业')),
                ('work_experience', models.TextField(blank=True, verbose_name='工作经历')),
                ('skills', models.TextField(blank=True, verbose_name='专业技能')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/', verbose_name='简历文件')),
                ('self_introduction', models.TextField(blank=True, verbose_name='自我介绍')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewing', '审核中'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('review_notes', models.TextField(blank=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_resumes', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '简历管理',
                'verbose_name_plural': '简历管理',
                'db_table': 'users_resume',
                'ordering': ['-created_at'],
            },
        ),
    ]
