# Generated by Django 4.2.7 on 2026-01-28 17:30

from django.db import migrations, connection


def migrate_auth_user_to_customuser(apps, schema_editor):
    """
    将 auth_user 表中的数据迁移到 users_customuser 表
    """
    # 获取模型
    CustomUser = apps.get_model('users', 'CustomUser')
    UserProfile = apps.get_model('users', 'UserProfile')
    
    # 使用原始 SQL 查询 auth_user 表
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT id, username, password, email, first_name, last_name, 
                   is_staff, is_active, is_superuser, date_joined, last_login
            FROM auth_user
            ORDER BY id
        """)
        auth_users = cursor.fetchall()
        
        for auth_user in auth_users:
            (user_id, username, password, email, first_name, last_name,
             is_staff, is_active, is_superuser, date_joined, last_login) = auth_user
            
            # 检查用户是否已存在
            if not CustomUser.objects.filter(username=username).exists():
                # 创建 CustomUser
                custom_user = CustomUser(
                    id=user_id,
                    username=username,
                    password=password,
                    email=email or '',
                    first_name=first_name or '',
                    last_name=last_name or '',
                    is_staff=is_staff,
                    is_active=is_active,
                    is_superuser=is_superuser,
                    date_joined=date_joined,
                    last_login=last_login,
                    created_at=date_joined,  # 使用 date_joined 作为 created_at
                    updated_at=last_login or date_joined  # 使用 last_login 或 date_joined 作为 updated_at
                )
                custom_user.save()
                
                # 创建 UserProfile（使用 get_or_create 避免重复）
                profile, created = UserProfile.objects.get_or_create(user=custom_user)
                if created:
                    print(f"已迁移用户: {username}，并创建了 UserProfile")
                else:
                    print(f"已迁移用户: {username}，UserProfile 已存在")
            else:
                print(f"用户 {username} 已存在，跳过迁移")


def reverse_migrate_auth_user_to_customuser(apps, schema_editor):
    """
    回滚操作：从 users_customuser 表删除迁移的数据
    """
    # 这里我们保留所有用户，因为回滚可能会导致数据丢失
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            migrate_auth_user_to_customuser,
            reverse_migrate_auth_user_to_customuser,
        ),
    ]
