# Generated by Django 4.2.7 on 2026-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_delete_usercategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_category",
            field=models.CharField(
                choices=[
                    ("job_seeker", "求职者"),
                    ("researcher", "研究员"),
                    ("investor", "投资者"),
                    ("partner", "合作伙伴"),
                    ("other", "其他"),
                ],
                default="job_seeker",
                max_length=50,
                verbose_name="用户类型",
            ),
        ),
    ]
