# Generated by Django 4.2.7 on 2026-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogRotationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("app", "Application"),
                            ("error", "Error"),
                            ("security", "Security"),
                            ("performance", "Performance"),
                            ("django", "Django"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "max_size_mb",
                    models.IntegerField(default=10, help_text="Maximum log file size in MB"),
                ),
                (
                    "max_files",
                    models.IntegerField(default=10, help_text="Maximum number of archived files"),
                ),
                (
                    "max_age_days",
                    models.IntegerField(
                        default=30, help_text="Maximum age of archived files in days"
                    ),
                ),
                (
                    "compress_old",
                    models.BooleanField(default=True, help_text="Compress old log files"),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, help_text="Enable automatic rotation"),
                ),
                ("last_rotated", models.DateTimeField(blank=True, null=True)),
                ("is_manually_paused", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Log Rotation Configuration",
                "verbose_name_plural": "Log Rotation Configurations",
                "db_table": "log_rotation_config",
            },
        ),
        migrations.CreateModel(
            name="LogViewerAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("user_id", models.IntegerField(db_index=True)),
                ("username", models.CharField(max_length=150)),
                ("action", models.CharField(db_index=True, max_length=50)),
                ("log_type", models.CharField(blank=True, max_length=20, null=True)),
                ("filters_applied", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "log_viewer_access_log",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="SystemLogIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("logger", models.CharField(db_index=True, max_length=255)),
                ("message", models.TextField()),
                (
                    "trace_id",
                    models.CharField(blank=True, db_index=True, default="-", max_length=64),
                ),
                ("request_id", models.CharField(blank=True, default="-", max_length=32)),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("app", "Application"),
                            ("error", "Error"),
                            ("security", "Security"),
                            ("performance", "Performance"),
                            ("django", "Django"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("file_offset", models.BigIntegerField(help_text="Byte offset in log file")),
                ("line_number", models.IntegerField()),
                ("indexed", models.BooleanField(db_index=True, default=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "system_log_index",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["log_type", "-timestamp"], name="system_log__log_typ_8f4db0_idx"
                    ),
                    models.Index(
                        fields=["trace_id", "-timestamp"], name="system_log__trace_i_50360b_idx"
                    ),
                    models.Index(
                        fields=["level", "-timestamp"], name="system_log__level_93e293_idx"
                    ),
                    models.Index(
                        fields=["user_id", "-timestamp"], name="system_log__user_id_3c9584_idx"
                    ),
                ],
            },
        ),
    ]
