# Generated by Django 3.2.11 on 2022-03-17 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericStockMarketData',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_code', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('stock_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_price', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_time', models.DateTimeField(blank=True)),
                ('source_data', models.TextField(default='')),
            ],
            options={
                'verbose_name': '股票市场历史数据',
                'verbose_name_plural': '股票市场历史数据',
            },
        ),
    ]
