# Generated by Django 3.2.11 on 2022-03-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_apps', '0003_auto_20220317_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericstockmarketdata',
            old_name='close',
            new_name='close_price',
        ),
        migrations.RenameField(
            model_name='genericstockmarketdata',
            old_name='high',
            new_name='high_price',
        ),
        migrations.RenameField(
            model_name='genericstockmarketdata',
            old_name='low',
            new_name='low_price',
        ),
        migrations.RenameField(
            model_name='genericstockmarketdata',
            old_name='open',
            new_name='open_price',
        ),
    ]
