# Generated by Django 3.2.11 on 2022-06-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_apps', '0004_auto_20220318_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastStorckMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stock_code', models.CharField(max_length=16, unique=True)),
                ('stock_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='genericstockmarketdata',
            options={'ordering': ['current_time'], 'verbose_name': '股票市场历史数据', 'verbose_name_plural': '股票市场历史数据'},
        ),
    ]
