# Generated by Django 4.2.7 on 2026-01-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousls',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='productpics',
            name='product',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Recruits',
        ),
        migrations.DeleteModel(
            name='ProductCats',
        ),
        migrations.DeleteModel(
            name='ProductPics',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductTags',
        ),
    ]
