# Generated by Django 4.2.7 on 2026-01-30 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companyinfo", "0002_delete_carousls_delete_news_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="岗位名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("quant_dev", "量化开发"),
                            ("data_engineer", "数据工程师"),
                            ("risk_manager", "风控专员"),
                            ("researcher", "研究员"),
                            ("it_support", "IT支持"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="岗位类别",
                    ),
                ),
                (
                    "recruitment_type",
                    models.CharField(
                        choices=[("campus", "校园招聘"), ("social", "社会招聘")],
                        default="social",
                        max_length=20,
                        verbose_name="招聘类型",
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=50, verbose_name="部门")),
                ("location", models.CharField(blank=True, max_length=100, verbose_name="工作地点")),
                ("description", models.TextField(blank=True, verbose_name="岗位职责")),
                ("requirements", models.TextField(blank=True, verbose_name="任职要求")),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=100, verbose_name="薪资范围"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否招聘中")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "招聘岗位",
                "verbose_name_plural": "招聘岗位管理",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("email", models.EmailField(max_length=254, verbose_name="电子邮箱")),
                (
                    "job_category",
                    models.CharField(
                        choices=[
                            ("quant_dev", "量化开发"),
                            ("data_engineer", "数据工程师"),
                            ("risk_manager", "风控专员"),
                            ("researcher", "研究员"),
                            ("it_support", "IT支持"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="应聘职位类别",
                    ),
                ),
                (
                    "expected_salary",
                    models.CharField(blank=True, max_length=50, verbose_name="期望薪资"),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "高中"),
                            ("associate", "大专"),
                            ("bachelor", "本科"),
                            ("master", "硕士"),
                            ("doctor", "博士"),
                        ],
                        max_length=20,
                        verbose_name="最高学历",
                    ),
                ),
                ("school", models.CharField(blank=True, max_length=100, verbose_name="毕业院校")),
                ("major", models.CharField(blank=True, max_length=100, verbose_name="专业")),
                ("work_experience", models.TextField(blank=True, verbose_name="工作经历")),
                ("skills", models.TextField(blank=True, verbose_name="专业技能")),
                ("self_introduction", models.TextField(blank=True, verbose_name="自我介绍")),
                (
                    "resume_file",
                    models.FileField(
                        blank=True, null=True, upload_to="resumes/%Y/%m/", verbose_name="简历文件"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "待查看"),
                            ("viewed", "已查看"),
                            ("interview", "待面试"),
                            ("hired", "已录用"),
                            ("rejected", "已拒绝"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=100, verbose_name="审核人"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="投递时间")),
                (
                    "position",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companyinfo.jobposition",
                        verbose_name="应聘岗位",
                    ),
                ),
            ],
            options={
                "verbose_name": "收到的简历",
                "verbose_name_plural": "简历管理",
                "ordering": ["-created_at"],
            },
        ),
    ]
