# Generated by Django 4.2.7 on 2026-01-30 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0003_add_jobposition_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advantages',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='IndexAsk',
        ),
    ]
