# Generated by Django 4.2.7

from django.db import migrations


def add_sample_positions(apps, schema_editor):
    JobPosition = apps.get_model('companyinfo', 'JobPosition')

    # 校园招聘职位
    campus_positions = [
        {
            'title': '量化开发工程师（实习生）',
            'category': 'quant_dev',
            'recruitment_type': 'campus',
            'department': '量化研发部',
            'location': '上海',
            'salary_range': '300-500元/天',
            'description': '''负责量化交易策略的开发与优化
参与因子研究、模型构建和回测分析
协助开发数据处理和交易执行系统''',
            'requirements': '''本科及以上学历，数学、统计、金融工程、计算机等相关专业
熟练掌握Python/C++，有量化开发或机器学习项目经验
对金融市场有浓厚兴趣，具备良好的逻辑思维能力
每周可实习3天以上''',
            'sort_order': 1,
        },
        {
            'title': '数据工程师（实习生）',
            'category': 'data_engineer',
            'recruitment_type': 'campus',
            'department': '技术部',
            'location': '上海',
            'salary_range': '250-400元/天',
            'description': '''参与金融数据仓库建设
开发数据采集、清洗和存储流程
协助优化数据处理性能和稳定性''',
            'requirements': '''本科及以上学历，计算机、软件工程等相关专业
熟悉Python、SQL，了解大数据技术（Hadoop/Spark）
有数据处理或ETL开发经验优先
每周可实习3天以上''',
            'sort_order': 2,
        },
        {
            'title': '量化研究员（实习生）',
            'category': 'researcher',
            'recruitment_type': 'campus',
            'department': '研究部',
            'location': '上海',
            'salary_range': '300-500元/天',
            'description': '''协助进行量化策略的研究与分析
参与市场数据分析和因子挖掘
支持投资组合优化相关工作''',
            'requirements': '''硕士及以上学历，金融、数学、统计、物理等相关专业
熟练使用Python/R进行数据分析
具备扎实的统计学和机器学习基础
每周可实习3天以上''',
            'sort_order': 3,
        },
    ]

    # 社会招聘职位
    social_positions = [
        {
            'title': '高级量化开发工程师',
            'category': 'quant_dev',
            'recruitment_type': 'social',
            'department': '量化研发部',
            'location': '上海',
            'salary_range': '40K-80K·15薪',
            'description': '''负责核心量化交易系统的架构设计与开发
主导高性能回测平台和实盘交易系统的研发
优化交易执行算法，降低滑点成本
带领团队进行技术创新和性能优化''',
            'requirements': '''5年以上量化开发经验，熟悉量化交易流程
精通C++/Python，深入理解多线程、网络编程和内存管理
有低延迟交易系统开发经验，熟悉内存数据库和消息队列
具备良好的团队协作和项目管理能力''',
            'sort_order': 1,
        },
        {
            'title': '量化策略研究员',
            'category': 'researcher',
            'recruitment_type': 'social',
            'department': '研究部',
            'location': '上海',
            'salary_range': '30K-60K·15薪',
            'description': '''开发并维护量化交易策略
进行因子研究和模型开发
进行策略回测、优化和实盘跟踪
与开发团队协作实现策略落地''',
            'requirements': '''3年以上量化策略研发经验，有实盘业绩
精通Python/R，熟悉机器学习和深度学习框架
具备扎实的数学建模和统计分析能力
有机器学习策略开发经验优先''',
            'sort_order': 2,
        },
        {
            'title': '数据工程师',
            'category': 'data_engineer',
            'recruitment_type': 'social',
            'department': '技术部',
            'location': '上海',
            'salary_range': '20K-40K·15薪',
            'description': '''负责金融数据平台的建设与维护
设计和实现高效的数据采集、清洗和存储方案
优化数据处理流程，提升数据质量和服务稳定性
支持业务部门的数据需求''',
            'requirements': '''3年以上数据开发经验，熟悉数据仓库建设
精通Python/SQL，了解Spark、Flink等大数据技术
有金融数据处理经验优先
具备良好的问题分析和解决能力''',
            'sort_order': 3,
        },
        {
            'title': '风控专员',
            'category': 'risk_manager',
            'recruitment_type': 'social',
            'department': '风控部',
            'location': '上海',
            'salary_range': '18K-35K·15薪',
            'description': '''制定和优化风险控制策略
监控投资组合风险指标，进行风险预警
参与压力测试和情景分析
完善风险管理制度和流程''',
            'requirements': '''3年以上金融风控经验，熟悉量化风控指标
精通Python/SQL，具备数据分析能力
熟悉期货、期权等衍生品风险模型
持有FRM/CFA证书优先''',
            'sort_order': 4,
        },
        {
            'title': 'IT支持工程师',
            'category': 'it_support',
            'recruitment_type': 'social',
            'department': '技术部',
            'location': '上海',
            'salary_range': '12K-20K·15薪',
            'description': '''负责日常IT运维和技术支持
维护办公设备和网络系统
支持业务系统的部署和升级
协助解决用户技术问题''',
            'requirements': '''2年以上IT支持经验，熟悉Windows/Linux系统
了解网络架构和常见故障排查
有ITIL或运维经验优先
具备良好的服务意识和沟通能力''',
            'sort_order': 5,
        },
    ]

    for pos in campus_positions:
        JobPosition.objects.create(**pos)

    for pos in social_positions:
        JobPosition.objects.create(**pos)


def remove_sample_positions(apps, schema_editor):
    JobPosition = apps.get_model('companyinfo', 'JobPosition')
    JobPosition.objects.filter(
        title__in=[
            '量化开发工程师（实习生）',
            '数据工程师（实习生）',
            '量化研究员（实习生）',
            '高级量化开发工程师',
            '量化策略研究员',
            '数据工程师',
            '风控专员',
            'IT支持工程师',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0004_delete_advantages_delete_comments_delete_indexask'),
    ]

    operations = [
        migrations.RunPython(add_sample_positions, remove_sample_positions),
    ]
