# Generated by Django 4.2.7 on 2026-02-01 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companyinfo", "0004_delete_advantages_delete_comments_delete_indexask"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GetMessages",
        ),
    ]
