# Generated by Django 4.2.7 on 2026-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="策略名称")),
                ("initial_capital", models.FloatField(default=1000000, verbose_name="初始资金")),
                ("final_value", models.FloatField(verbose_name="最终价值")),
                ("total_return", models.FloatField(verbose_name="总收益率(%)")),
                ("annual_return", models.FloatField(verbose_name="年化收益率(%)")),
                ("max_drawdown", models.FloatField(verbose_name="最大回撤(%)")),
                ("sharpe_ratio", models.FloatField(verbose_name="夏普比率")),
                ("win_rate", models.FloatField(verbose_name="胜率(%)")),
                ("params", models.JSONField(default=dict, verbose_name="策略参数")),
                ("result_data", models.JSONField(default=dict, verbose_name="结果数据")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "回测结果",
                "verbose_name_plural": "回测结果",
            },
        ),
        migrations.CreateModel(
            name="FactorComputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="因子名称")),
                ("symbol", models.CharField(max_length=20, verbose_name="股票代码")),
                ("date", models.DateField(verbose_name="日期")),
                ("value", models.FloatField(verbose_name="因子值")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "因子计算",
                "verbose_name_plural": "因子计算",
                "indexes": [
                    models.Index(
                        fields=["name", "symbol", "date"], name="factorhub_f_name_7d7f06_idx"
                    )
                ],
            },
        ),
    ]
