# Generated by Django 4.2.7 on 2026-02-01 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='报告内容')),
                ('strategy_name', models.CharField(blank=True, max_length=100, verbose_name='策略名称')),
                ('strategy_type', models.CharField(blank=True, max_length=50, verbose_name='策略类型')),
                ('market', models.CharField(blank=True, max_length=50, verbose_name='适用市场')),
                ('annual_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='年化收益率')),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大回撤')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='夏普比率')),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='胜率')),
                ('profit_loss_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='盈亏比')),
                ('total_trades', models.IntegerField(default=0, verbose_name='总交易次数')),
                ('backtest_start_date', models.DateField(blank=True, null=True, verbose_name='回测开始日期')),
                ('backtest_end_date', models.DateField(blank=True, null=True, verbose_name='回测结束日期')),
                ('strategy_params', models.JSONField(blank=True, default=dict, verbose_name='策略参数')),
                ('equity_curve_image', models.ImageField(blank=True, null=True, upload_to='reports/equity/%Y/%m/', verbose_name='资金曲线图')),
                ('drawdown_image', models.ImageField(blank=True, null=True, upload_to='reports/drawdown/%Y/%m/', verbose_name='回撤图')),
                ('monthly_returns_image', models.ImageField(blank=True, null=True, upload_to='reports/monthly/%Y/%m/', verbose_name='月度收益图')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='reports/files/%Y/%m/', verbose_name='附件')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='标签')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('published', '已发布')], default='draft', max_length=20, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_notes', models.TextField(blank=True, verbose_name='审核备注')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('view_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_reports', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '研究报告',
                'verbose_name_plural': '研究报告管理',
                'ordering': ['-is_top', '-published_at', '-created_at'],
            },
        ),
    ]
