# Generated by Django 3.0.6 on 2022-03-15 16:13

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='产品优势', max_length=10, verbose_name='标题')),
                ('img', models.ImageField(upload_to='advantages', verbose_name='图标')),
                ('info', models.CharField(default='产品优势', max_length=50, verbose_name='内容')),
            ],
            options={
                'verbose_name': '产品优势',
                'verbose_name_plural': '产品优势',
            },
        ),
        migrations.CreateModel(
            name='Carousls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('img', models.ImageField(upload_to='carousls', verbose_name='轮播图')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='市区')),
            ],
            options={
                'verbose_name': '市区',
                'verbose_name_plural': '市区',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='游客IP')),
                ('msg', models.CharField(max_length=200, verbose_name='留言')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
                ('category', models.CharField(choices=[('cp', '产品'), ('xw', '新闻'), ('al', '案例')], default='cp', max_length=2, verbose_name='评论分类')),
                ('obj_pk', models.IntegerField(verbose_name='评论对象')),
                ('reply', models.TextField(default='', verbose_name='回复')),
                ('is_display', models.BooleanField(default=False, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '评论管理',
                'verbose_name_plural': '评论管理',
            },
        ),
        migrations.CreateModel(
            name='FriendlyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='标题')),
                ('friendly_link', models.URLField(verbose_name='链接')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='GetMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('phone', models.CharField(max_length=15, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('msg', models.TextField(verbose_name='留言')),
                ('is_handle', models.BooleanField(default=False, verbose_name='处理')),
            ],
            options={
                'verbose_name': '留言管理',
                'verbose_name_plural': '留言管理',
            },
        ),
        migrations.CreateModel(
            name='IndexAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='标题')),
                ('info', models.CharField(max_length=50, verbose_name='内容')),
            ],
            options={
                'verbose_name': '首页咨询',
                'verbose_name_plural': '首页咨询',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('category', models.CharField(choices=[('gsxw', '公司新闻'), ('mtbd', '媒体报道'), ('yggh', '员工关怀')], default='gsxw', max_length=4, verbose_name='所属分类')),
                ('img', models.ImageField(upload_to='news', verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('click_nums', models.IntegerField(default=0, verbose_name='人气')),
                ('digest', models.CharField(default='', max_length=50, verbose_name='摘要')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='新闻内容')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='点赞数')),
                ('oppose_nums', models.IntegerField(default=0, verbose_name='反对数')),
            ],
            options={
                'verbose_name': '新闻动态',
                'verbose_name_plural': '新闻动态',
            },
        ),
        migrations.CreateModel(
            name='ProductCats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
            },
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签')),
            ],
            options={
                'verbose_name': '产品标签',
                'verbose_name_plural': '产品标签',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('category', models.CharField(choices=[('trxf', '土壤修复类'), ('wszl', '污水治理类'), ('shlj', '生活垃圾发电类')], default='trxf', max_length=4, verbose_name='所属分类')),
                ('img', models.ImageField(upload_to='projects', verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('click_nums', models.IntegerField(default=0, verbose_name='人气')),
                ('digest', models.CharField(default='', max_length=60, verbose_name='摘要')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='工程内容')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='点赞数')),
                ('oppose_nums', models.IntegerField(default=0, verbose_name='反对数')),
            ],
            options={
                'verbose_name': '工程案例',
                'verbose_name_plural': '工程案例',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='省份')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
        migrations.CreateModel(
            name='Recruits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rcln', '人才理念'), ('zwfb', '职位发布')], default='rcln', max_length=4, verbose_name='所属分类')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '人才招聘',
                'verbose_name_plural': '人才招聘',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('img', models.ImageField(upload_to='productpic', verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('click_nums', models.IntegerField(default=0, verbose_name='人气')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='产品内容')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website_info.ProductCats', verbose_name='所属分类')),
                ('tag', models.ManyToManyField(to='website_info.ProductTags')),
            ],
            options={
                'verbose_name': '产品中心',
                'verbose_name_plural': '产品中心',
            },
        ),
        migrations.CreateModel(
            name='ProductPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('img', models.ImageField(upload_to='productpic', verbose_name='产品图片')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website_info.Products', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='北京源码商城有限公司', max_length=50, verbose_name='公司名称')),
                ('logo', models.ImageField(upload_to='website_info', verbose_name='logo')),
                ('address', models.CharField(default='', max_length=200, verbose_name='详细地址')),
                ('phone', models.CharField(default='+86 0000 96877', max_length=15, verbose_name='电话')),
                ('fax', models.CharField(default='+86 0000 96877', max_length=15, verbose_name='传真')),
                ('postcode', models.CharField(default='000000', max_length=15, verbose_name='邮编')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('linkman', models.CharField(default='梦小白', max_length=10, verbose_name='联系人')),
                ('telephone', models.CharField(default='+86 0000 96877', max_length=15, verbose_name='联系电话')),
                ('digest', models.CharField(default='', max_length=300, verbose_name='关于我们摘要')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='公司简介')),
                ('honor', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='荣誉资质')),
                ('qrcode', models.ImageField(upload_to='website_info', verbose_name='微信二维码')),
                ('weichat', models.CharField(default='', max_length=50, verbose_name='微信号')),
                ('qq', models.CharField(default='888888888', max_length=15, verbose_name='客服QQ')),
                ('record_nums', models.CharField(default='京ICP备00000000号', max_length=50, verbose_name='备案号')),
                ('topimg', models.ImageField(upload_to='website_info', verbose_name='非首页顶长图')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website_info.City', verbose_name='市区')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website_info.Province', verbose_name='省份'),
        ),
    ]
