# Generated by Django 3.0.6 on 2021-12-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_second_page', '0002_companysecondpagebannerimage_info_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysecondpage',
            name='body',
        ),
    ]
