# Generated by Django 3.2.11 on 2022-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_data', '0002_alter_genericstockmarketdata_stock_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericstockmarketdata',
            old_name='stock_time',
            new_name='current_time',
        ),
        migrations.RenameField(
            model_name='genericstockmarketdata',
            old_name='stock_price',
            new_name='now_price',
        ),
        migrations.AddField(
            model_name='genericstockmarketdata',
            name='close',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='昨日收盘价'),
        ),
        migrations.AddField(
            model_name='genericstockmarketdata',
            name='high',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='今日最高价'),
        ),
        migrations.AddField(
            model_name='genericstockmarketdata',
            name='low',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='今日最低价'),
        ),
        migrations.AddField(
            model_name='genericstockmarketdata',
            name='open',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='今日开盘价'),
        ),
        migrations.AddField(
            model_name='genericstockmarketdata',
            name='trading_volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='成交金额'),
        ),
        migrations.AddField(
            model_name='genericstockmarketdata',
            name='turnover_of_shares',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='股票成交数'),
        ),
    ]
