# Generated by Django 3.0.6 on 2021-12-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_index_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyIndexPageAdvantagesImage',
        ),
    ]
