# Generated by Django 3.0.6 on 2021-12-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_index_page', '0002_delete_companyindexpageadvantagesimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyindexpagebannerimage',
            name='info_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
